In [1]:
def readInteractions(f_name):
	try:
		f_handle = open(f_name,"r")
	except IOError as e:
		print("I/O error: can't open interactions file.")
		sys.exit()


	interactions = []
	int_file = open(f_name,"r")
	for line in int_file:
		interactions.append(line.strip().split(sep=","))
		interactions[-1][3] = (float(interactions[-1][3]))**2
		interactions[-1][4] = (float(interactions[-1][4]))**2
		if(interactions[-1][1] > interactions[-1][2]):
			temp = interactions[-1][1]
			interactions[-1][1] = interactions[-1][2]
			interactions[-1][2] = temp

	f_handle.close()
	int_list = sorted(set([i[0] for i in interactions]))

	return interactions, int_list

In [2]:
f_name = 'interactions.csv'
result = readInteractions(f_name)
interactions = result[0]
int_list = result[1]

print(interactions)
print('br')
print(int_list)

[['ARM_STACK', 'ARM', 'ARM', 2.25, 12.25], ['H_BOND', 'ACP', 'DON', 4.0, 9.0], ['HYDROPHOBIC', 'HPB', 'HPB', 4.0, 14.44], ['REPULSIVE', 'POS', 'POS', 4.0, 36.0], ['REPULSIVE', 'NEG', 'NEG', 4.0, 36.0], ['SALT_BRIDGE', 'NEG', 'POS', 4.0, 36.0]]
br
['ARM_STACK', 'HYDROPHOBIC', 'H_BOND', 'REPULSIVE', 'SALT_BRIDGE']


In [3]:
def __str__interactions(interactions):
	temp = ""
	x = 0
	for i in interactions:
		#print(i[0][4]) 
		#print(x)
		temp += "%-12s| %s-%s | %5.2f -%6.2f\n" %(i[0],i[1],i[2],i[3],i[4]) 
		x=x+1
	return temp

In [4]:
def printInteractions(interactions):
	print(__str__interactions(interactions))

In [5]:
printInteractions(interactions)

ARM_STACK   | ARM-ARM |  2.25 - 12.25
H_BOND      | ACP-DON |  4.00 -  9.00
HYDROPHOBIC | HPB-HPB |  4.00 - 14.44
REPULSIVE   | POS-POS |  4.00 - 36.00
REPULSIVE   | NEG-NEG |  4.00 - 36.00
SALT_BRIDGE | NEG-POS |  4.00 - 36.00



In [6]:
def readAtom_Types(f_name):
	try:
		f_handle = open(f_name,"r")
	except IOError as e:
		print("I/O error: can't open atom types file.")
		sys.exit()

        
	types = set() # initialize with an empty set
	atm_data = dict() # initialize with an empty dictionary

	temp = [] # declearing an empty array
	res_name = ""
	for line in f_handle:
		temp = line.strip('\n').split(",") 
		if res_name != temp[0]:
			atm_data[temp[0]] = dict() 
			res_name = temp[0]
		atm_data[res_name][temp[1]] = [ i for i in temp[2:]]
		types |= set(temp[2:])
	f_handle.close()

	types = sorted(types)
	return atm_data,types

In [7]:
f_name = "atom_types.csv";
result = readAtom_Types(f_name)

atm_data = result[0]
types = result[1]

a_types = atm_data

a_type_list = types

print(a_types)
print('br')
print(a_type_list)

{'ALA': {'N': ['DON'], 'CA': [], 'C': [], 'O': ['ACP'], 'CB': ['HPB']}, 'ARG': {'N': ['DON'], 'CA': [], 'C': [], 'O': ['ACP'], 'CB': ['HPB'], 'CG': ['HPB'], 'CD': [], 'NE': ['POS', 'DON'], 'CZ': ['POS'], 'NH1': ['POS', 'DON'], 'NH2': ['POS', 'DON']}, 'ASN': {'N': ['DON'], 'CA': [], 'C': [], 'O': ['ACP'], 'CB': ['HPB'], 'CG': [], 'OD1': ['ACP'], 'ND2': ['DON']}, 'ASP': {'N': ['DON'], 'CA': [], 'C': [], 'O': ['ACP'], 'CB': ['HPB'], 'CG': [], 'OD1': ['NEG', 'ACP'], 'OD2': ['NEG', 'ACP']}, 'CYS': {'N': ['DON'], 'CA': [], 'C': [], 'O': ['ACP'], 'CB': ['HPB'], 'SG': ['DON', 'ACP', 'SSB']}, 'GLN': {'N': ['DON'], 'CA': [], 'C': [], 'O': ['ACP'], 'CB': ['HPB'], 'CG': ['HPB'], 'CD': [], 'OE1': ['ACP'], 'NE2': ['DON']}, 'GLU': {'N': ['DON'], 'CA': [], 'C': [], 'O': ['ACP'], 'CB': ['HPB'], 'CG': ['HPB'], 'CD': [], 'OE1': ['NEG', 'ACP'], 'OE2': ['NEG', 'ACP']}, 'GLY': {'N': ['DON'], 'CA': [], 'C': [], 'O': ['ACP']}, 'HIS': {'N': ['DON'], 'CA': [], 'C': [], 'O': ['ACP'], 'CB': ['HPB'], 'CG': ['ARM']

In [8]:
def __str__Atom_Types(atm_data):

	temp = ""
	for k, v in sorted(atm_data.items()):
		temp += "\n" + k.__str__()
		#print(temp)
		for i, j in sorted(v.items()):
			temp += "\n %6s |" % (i.__str__())
			for typ in sorted(j):
				temp += "%4s" % typ
	
	return temp

In [9]:
def printAtom_Types(atm_data):
	print(__str__Atom_Types(atm_data))

In [10]:
print(printAtom_Types(atm_data))


ALA
      C |
     CA |
     CB | HPB
      N | DON
      O | ACP
ARG
      C |
     CA |
     CB | HPB
     CD |
     CG | HPB
     CZ | POS
      N | DON
     NE | DON POS
    NH1 | DON POS
    NH2 | DON POS
      O | ACP
ASN
      C |
     CA |
     CB | HPB
     CG |
      N | DON
    ND2 | DON
      O | ACP
    OD1 | ACP
ASP
      C |
     CA |
     CB | HPB
     CG |
      N | DON
      O | ACP
    OD1 | ACP NEG
    OD2 | ACP NEG
CYS
      C |
     CA |
     CB | HPB
      N | DON
      O | ACP
     SG | ACP DON SSB
GLN
      C |
     CA |
     CB | HPB
     CD |
     CG | HPB
      N | DON
    NE2 | DON
      O | ACP
    OE1 | ACP
GLU
      C |
     CA |
     CB | HPB
     CD |
     CG | HPB
      N | DON
      O | ACP
    OE1 | ACP NEG
    OE2 | ACP NEG
GLY
      C |
     CA |
      N | DON
      O | ACP
HIS
      C |
     CA |
     CB | HPB
    CD2 | ARM
    CE1 | ARM
     CG | ARM
      N | DON
    ND1 | ACP ARM DON POS
    NE2 | ACP ARM DON POS
      O | ACP
ILE
      C |
 

In [11]:
class TypeCode:
	def __init__(self,atom_types,int_types):
		
		type_map = enumerate(sorted(atom_types) + sorted(int_types))
		#print(list(type_map))
		self.type_map = {v:(1<<k) for k,v in type_map}
		#print(self.type_map)
		self.keys = sorted(self.type_map.values())
		self.rev = {k:v for v,k in self.type_map.items()}
		print(self.type_map)

	def __getitem__(self,t):
		return self.type_map[t]


	def get_rev(self,n):
		return self.rev[n]

	def type(self,n):
		return [self.rev[i] for i in filter(lambda x: x & n,self.keys)]
	
	def code(self,n):
		return [i for i in filter(lambda x: x & n,self.keys)]

	def len(self):
		return len(self.type_map)

	def max(self):
		return 1<<(self.len()-1)

	def __str__(self):
		return self.type_map.__str__()
		

In [12]:
typeCode = TypeCode(a_type_list,int_list)

{'ACP': 1, 'ARM': 2, 'DON': 4, 'HPB': 8, 'NEG': 16, 'POS': 32, 'SSB': 64, 'ARM_STACK': 128, 'HYDROPHOBIC': 256, 'H_BOND': 512, 'REPULSIVE': 1024, 'SALT_BRIDGE': 2048}


In [13]:
import json


class TypeMap:
	def __init__(self,json_file):
		with open(json_file,"r") as json_file_holder:
			self.type_map = json.loads(json_file_holder.read())

	def __str__(self):
		return self.type_map.__str__()

	def __getitem__(self,t):
		return self.type_map[t]

In [14]:
f_name = "typenames.json"
typenames = TypeMap(f_name)
print (typenames)

{'ACP': 'Acceptor', 'DON': 'Donor', 'POS': 'Positive', 'NEG': 'Negative', 'HPB': 'Hydrophobic', 'ARM': 'Aromatic', 'HYDROPHOBIC': 'Hydrophobic', 'SALT_BRIDGE': 'Salt bridge', 'ARM_STACK': 'Aromatic', 'H_BOND': 'Hydrogen bond', 'REPULSIVE': 'Repulsive', 'SS_BRIDGE': 'Disulfide Bridge'}


In [15]:
	import os
	import sys
	from pathlib import Path 
	#GSPANPATH = os.getcwd() + "/result"
	GSPANPATH = os.getcwd() + "/gSpan/gSpan-64"
	pdbids_file = "soybean.txt"
	path = Path(GSPANPATH)


In [16]:
	import logging
	path.mkdir(parents=True,exist_ok=True)
	path = str(path)
		
	logging.basicConfig(level=logging.DEBUG)
	

    

In [17]:
def read_pdbid_file(filename):
	chains = dict()
	with open(filename,"r") as input_pdbs:
		chains = list(map(lambda x: x.split(","),input_pdbs.read().split("\n")))
		chains = list(filter(lambda x: x[0][0] != "#",chains))
		chains = [[c[0]] + [(c[2*n+1],c[2*n+2]) for n in range(len(c)//2)] for c in chains]
		
		chains = {k:v for k,v in [(i[0],i[1:]) for i in chains] }

	pdbids = sorted(chains.keys())

	return pdbids,chains

In [18]:
pdbids, chains = read_pdbid_file(pdbids_file)

In [19]:
print (pdbids)

['1AN1', '1AVW', '1BRB', '1BRC', '1C9P', '1CO7', '1EJA', '1EJM', '1EZS', '1EZU', '1F2S', '1F5R', '1F7Z', '1FY8', '1H9H', '1H9I', '1JRS', '1JRT', '1K9O', '1LDT', '1MCT', '1OPH', '1P2I', '1P2J', '1P2K', '1PPE', '1SBW', '1SFI', '1SLV', '1SLW', '1SLX', '1SMF', '1TAW', '1TFX', '1TPA', '1TPS', '1YLC', '1YLD', '1Z7K', '2AGE', '2AGG', '2AGI', '2BTC', '2FI3', '2FI4', '2FI5', '2FTL', '2FTM', '2PTC', '2RA3', '2TGP', '2TPI', '3BTD', '3BTF', '3BTG', '3BTH', '3BTK', '3BTM', '3BTQ', '3BTT', '3BTW', '3D65', '3E8L', '3FP6', '3FP7', '3FP8', '3MYW', '3OTJ', '3P92', '3P95', '3RDZ', '3TGI', '3TGJ', '3TGK', '3TPI', '4ABI', '4ABJ', '4AN7', '4AOQ', '4AOR', '4DOQ', '4HGC', '4J2Y', '4KTS', '4KTU', '4TPI', '4U2W', '4U30', '4WXV', '4Y0Y', '4Y0Z', '4Y10', '4Y11']


In [20]:
print (chains)

{'1AN1': [('E', 'I')], '1AVW': [('A', 'B')], '1BRB': [('E', 'I')], '1BRC': [('E', 'I')], '1C9P': [('A', 'B')], '1CO7': [('E', 'I')], '1EJA': [('A', 'B')], '1EJM': [('A', 'B'), ('C', 'D'), ('E', 'F')], '1EZS': [('C', 'A'), ('D', 'B')], '1EZU': [('C', 'A'), ('D', 'B')], '1F2S': [('E', 'I')], '1F5R': [('A', 'I')], '1F7Z': [('A', 'I')], '1FY8': [('E', 'I')], '1H9H': [('E', 'I')], '1H9I': [('E', 'I')], '1JRS': [('A', 'B')], '1JRT': [('A', 'B')], '1K9O': [('E', 'I')], '1LDT': [('T', 'L')], '1MCT': [('A', 'I')], '1OPH': [('B', 'A')], '1P2I': [('A', 'I')], '1P2J': [('A', 'I')], '1P2K': [('A', 'I')], '1PPE': [('E', 'I')], '1SBW': [('A', 'I')], '1SFI': [('A', 'I')], '1SLV': [('B', 'A')], '1SLW': [('B', 'A')], '1SLX': [('B', 'A')], '1SMF': [('E', 'I')], '1TAW': [('A', 'B')], '1TFX': [('A', 'C'), ('B', 'D')], '1TPA': [('E', 'I')], '1TPS': [('A', 'B')], '1YLC': [('A', 'B')], '1YLD': [('A', 'B')], '1Z7K': [('A', 'B'), ('A', 'C')], '2AGE': [('X', 'A')], '2AGG': [('X', 'A')], '2AGI': [('X', 'A')], '2B

In [21]:
def read_PDB_files(pdbids,directory="",show_info=True):

	path = Path.cwd() / directory
	path.mkdir(parents=True,exist_ok=True)

	# with open(pdbids) as input_pdbs:
	# 	pdbids = list(map(lambda x: x.split(","),input_pdbs.read().split("\n")))
	# 	pdbids = list(filter(lambda x: x[0][0] != "#",pdbids))

	pdb_structures = dict()
	info = dict()

	for i in pdbids:

		if (path / ("pdb%s.ent" %i.lower())).exists():
			f_name = str(path / ("pdb%s.ent" %i.lower()))

		elif (path / ("%s.pdb" %i.lower())).exists():
			f_name = str(path / ("%s.pdb" %i.lower()))

		else:
			f_name = pdbl().retrieve_pdb_file(pdb_code=i,pdir=directory,file_format='pdb')

    
		#chains = [i[2*n+1:2*n+3] for n in range(len(i)//2)]
		structure = PDBParser(QUIET=True).get_structure(i,f_name)

		pdb_structures[i] = structure
		
		num_models = len([j for j in structure.get_models()])
		if num_models > 1:
			info[i] = num_models
		
		#exit()
	#chains = {k:v for k,v in }
	# if show_info:
	# 	print("%d pdbs have multiple models:"%len(info))
	# 	for k,v in sorted(info.items()):
	# 		print("%s-(%d)"%(k,v))
	# 	print("Total number of models: %s"%sum(info.values()))

	return pdb_structures	

In [22]:
pip install Bio

Note: you may need to restart the kernel to use updated packages.


In [23]:
import Bio.PDB.PDBList as pdbl
from Bio.PDB import PDBParser, PDBIO


pdb_structures = read_PDB_files(pdbids,directory="pdbfiles")

In [24]:
print (pdb_structures)

{'1AN1': <Structure id=1AN1>, '1AVW': <Structure id=1AVW>, '1BRB': <Structure id=1BRB>, '1BRC': <Structure id=1BRC>, '1C9P': <Structure id=1C9P>, '1CO7': <Structure id=1CO7>, '1EJA': <Structure id=1EJA>, '1EJM': <Structure id=1EJM>, '1EZS': <Structure id=1EZS>, '1EZU': <Structure id=1EZU>, '1F2S': <Structure id=1F2S>, '1F5R': <Structure id=1F5R>, '1F7Z': <Structure id=1F7Z>, '1FY8': <Structure id=1FY8>, '1H9H': <Structure id=1H9H>, '1H9I': <Structure id=1H9I>, '1JRS': <Structure id=1JRS>, '1JRT': <Structure id=1JRT>, '1K9O': <Structure id=1K9O>, '1LDT': <Structure id=1LDT>, '1MCT': <Structure id=1MCT>, '1OPH': <Structure id=1OPH>, '1P2I': <Structure id=1P2I>, '1P2J': <Structure id=1P2J>, '1P2K': <Structure id=1P2K>, '1PPE': <Structure id=1PPE>, '1SBW': <Structure id=1SBW>, '1SFI': <Structure id=1SFI>, '1SLV': <Structure id=1SLV>, '1SLW': <Structure id=1SLW>, '1SLX': <Structure id=1SLX>, '1SMF': <Structure id=1SMF>, '1TAW': <Structure id=1TAW>, '1TFX': <Structure id=1TFX>, '1TPA': <Stru

In [25]:
def write_pdb_files(structures,chains,directory=""):

	path = Path(".") / directory
	path.mkdir(parents=True,exist_ok=True)
	#print(path)

	#print("write pdb files:")
	for pdbid,pdb_structure in structures.items():
		#print(pdbid)	
		# models = map(lambda x: x.get_id(),pdb_structure.get_models())
		io = PDBIO()
		io.set_structure(pdb_structure)
		# for models in models:
		for s,t in chains[pdbid]:
			#print(pair)
			fname = str(path/("%s.%s.pdb" %(pdbid,s)))
			io.save(fname,ChainSelect([s,t]))

In [26]:
class ChainSelect:
	def __init__(self,chains,model=0):
		self.chains = list(chains)
		self.model = model       

	def accept_chain(self,chain):
		if chain.get_id() in self.chains:
			#print(chain,chain.get_id())
			return True
		return False

	def accept_model(self,model):
		if model.get_id() == self.model:
			#print("File contains multiple models")
			return True
		return False

	def accept_residue(self,residue):
		return True

	def accept_atom(self,atom):
		return True

In [27]:
pdb_files = write_pdb_files(pdb_structures,chains,directory="pdbs")

In [28]:
def calc_contacts(pdb_obj,chains,interactions,atom_type,id="",ignore_models=True):
	
	if(ignore_models): 
		logging.warning("Ignoring multiple models in calc_contacts!")
	
	contacts = dict()

	for model in pdb_obj.get_models():
		
		model_contacts = dict()
		
		for chain1,chain2 in chains:
			atom_contacts = []
			
			####### Chain1
			atom_list1 = list(model[chain1].get_atoms())
			
			####### Chain2
			atom_list2 = list(model[chain2].get_atoms())
			
			####### Neighborhood Search data structure
			tree = NeighborSearch(atom_list2)
			for s_atom in atom_list1:
				if s_atom.parent.id[0] != " " or s_atom.name == "OXT":
					continue

				s_types = atom_type[s_atom.parent.resname].get(s_atom.name,[])

				if not s_types:
					continue
				
				for d_atom in tree.search(s_atom.coord,6,level="A"):
					
					if d_atom.parent.id[0] != " " or d_atom.name == "OXT":
						continue
					
					d_types = atom_type[d_atom.parent.resname].get(d_atom.name,[])
					
					if not d_types:
						continue
		
					for i in s_types:
						for j in d_types:
							count = 0
							for interaction in interactions:
								if sorted([i,j]) == sorted(interaction[1:3]):
									d = dist3D(s_atom.coord,d_atom.coord)
									if interaction[3] <= d <= interaction[4]:
										s = s_atom.serial_number
										contact = [s_atom,d_atom,interaction[0],i,j,d**0.5,s_types,d_types]
										
										atom_contacts.append(tuple(contact))
			
		#/////////////////////////////////////////////////////////////////////////////////////////////////////
		###### Output
			dtype = [('S_ATOM',object),('D_ATOM',object),('INTERACTION','U12'),('I_TYPE','U3'),
					('J_TYPE','U3'),('DISTANCE',float),('S_TYPES',object),('D_TYPES',object)]
			model_contacts_temp = np.array(atom_contacts,dtype=dtype)
			model_contacts[(chain1,chain2)] = model_contacts_temp

		contacts[model.get_id()] = model_contacts

		if ignore_models:
			break

	return contacts

def run_contacts(structures,chains,interactions,atom_type):
	contacts = dict()
	for pdbid in sorted(structures.keys()):
		contacts[pdbid] = calc_contacts(structures[pdbid],chains[pdbid],interactions,atom_type)

	return contacts

def dist3D(a,b):
	return (a[0]-b[0])**2 + (a[1]-b[1])**2 + (a[2]-b[2])**2 

In [29]:
from Bio.PDB import NeighborSearch
import sys, numpy as np
contacts = run_contacts(pdb_structures,chains,interactions,a_types)

In [30]:
print (contacts)

{'1AN1': {0: {('E', 'I'): array([(<Atom NZ>, <Atom NZ>, 'REPULSIVE', 'POS', 'POS', 4.61443499, list(['POS', 'DON']), list(['POS', 'DON'])),
       (<Atom OD1>, <Atom NZ>, 'SALT_BRIDGE', 'NEG', 'POS', 3.26393754, list(['NEG', 'ACP']), list(['POS', 'DON'])),
       (<Atom OD2>, <Atom NZ>, 'SALT_BRIDGE', 'NEG', 'POS', 3.71116705, list(['NEG', 'ACP']), list(['POS', 'DON'])),
       (<Atom O>, <Atom NZ>, 'H_BOND', 'ACP', 'DON', 2.90098741, list(['ACP']), list(['POS', 'DON'])),
       (<Atom OG>, <Atom NZ>, 'H_BOND', 'ACP', 'DON', 2.97493445, list(['DON', 'ACP']), list(['POS', 'DON'])),
       (<Atom CG>, <Atom CB>, 'HYDROPHOBIC', 'HPB', 'HPB', 3.66218714, list(['HPB']), list(['HPB'])),
       (<Atom CG>, <Atom CD1>, 'HYDROPHOBIC', 'HPB', 'HPB', 3.50306387, list(['HPB']), list(['HPB'])),
       (<Atom N>, <Atom O>, 'H_BOND', 'DON', 'ACP', 2.74349653, list(['DON']), list(['ACP'])),
       (<Atom O>, <Atom N>, 'H_BOND', 'ACP', 'DON', 2.9721055 , list(['ACP']), list(['DON'])),
       (<Atom CE2

In [31]:
def gen_graphs(contacts,typeCode,gfilename="graphs.txt",path=""):

	graphs = []

	for pdbid, contacts in sorted(contacts.items()):
		graphs += gen_graph(contacts,pdbid,typeCode)

	for i in range(len(graphs)):
		graphs[i].graph["id"] = i

	graphs_string = ""
	graphs_string =  "".join(["".join(i for i in nx.generate_gml(g)) + "#" for g in graphs])

	#Write graphs file
	with (Path(path)/gfilename).open(mode="w") as gfile:
		gfile.write(graphs_string)

	#Generate node and edge label sets
	node_labels = set()
	edge_labels = set()
	for g in graphs:
		node_labels |= set(nx.get_node_attributes(g,'type').values())
		edge_labels |= set(nx.get_edge_attributes(g,'type').values())
		
	node_labels = sorted(node_labels)
	edge_labels = sorted(edge_labels)

	edge_labels = fill_label_set(edge_labels)
	node_labels = fill_label_set(node_labels)
	
	return graphs, node_labels, edge_labels

def gen_graph(contacts,pdbid,typeCode):
	
	temp = []
	
	graphs_string = ""
	g_id=0
	
	for model_idx,model in sorted(contacts.items()):
		for chains,group in sorted(model.items()):
		#/////////////////////////////////////////////////////////////////////////////////////////////////////
		###### Graph Generation
			
			g = nx.Graph()
			
			for contact in group:
				#Atom 1
				full_id = contact[0].get_full_id()
				s_data = [('model',full_id[1]),('chain',full_id[2]),("isLigand", False),('residueNumber',full_id[3][1]),
							('residueName',contact[0].get_parent().get_resname()),("atomName",full_id[4][0])]
				s_atom = full_id

				#Atom 2
				full_id = contact[1].get_full_id()
				d_data = [('model',full_id[1]),('chain',full_id[2]),("isLigand", True),('residueNumber',full_id[3][1]),
							('residueName',contact[1].get_parent().get_resname()),("atomName",full_id[4][0])]
				d_atom = full_id

				#Add or Update Edge
				if(g.has_edge(s_atom,d_atom)):
					g[s_atom][d_atom]['type'] |= typeCode[contact[2]]
				else:
					g.add_edge(s_atom,d_atom,type=typeCode[contact[2]],distance=contact[5])
								
				node = g.nodes[s_atom]
				node["type"] = node.get('type',0) | typeCode[contact[3]]
				node.update(s_data)
				
				node = g.nodes[d_atom]
				node.update(d_data)
				node["type"] = node.get('type',0) | typeCode[contact[4]]

			###########Compute Components
			number_comp = nx.number_connected_components(g)
			serial = None
			
			for comp in nx.connected_components(g):
				g_temp = g.subgraph(comp)
				g_temp = nx.Graph(g_temp)				
				g_temp = nx.convert_node_labels_to_integers(g_temp)
				
				g_temp.graph['id'] = g_id
				g_id+=1

				g_temp.graph['pdbid'] = pdbid

				g_temp.graph['source'],g_temp.graph['target'] = chains

				temp.append(g_temp)
						
	return sorted(temp,key=lambda g: g.graph['id'])

def fill_label_set(label_set):
	max_label = max(label_set)
	i = 1

	new_labels = set(label_set)
	while i < max_label:
		new_labels.add(i)
		i*=2
	return sorted(list(new_labels))
			

In [32]:
import networkx as nx
graphs, node_labels, edge_labels = gen_graphs(contacts,typeCode,path=path)

In [33]:
print(graphs)

[<networkx.classes.graph.Graph object at 0x000001EB556574C0>, <networkx.classes.graph.Graph object at 0x000001EB556576D0>, <networkx.classes.graph.Graph object at 0x000001EB556575B0>, <networkx.classes.graph.Graph object at 0x000001EB55657220>, <networkx.classes.graph.Graph object at 0x000001EB6D324FD0>, <networkx.classes.graph.Graph object at 0x000001EB6D252B50>, <networkx.classes.graph.Graph object at 0x000001EB6D324430>, <networkx.classes.graph.Graph object at 0x000001EB55657160>, <networkx.classes.graph.Graph object at 0x000001EB6D32E5E0>, <networkx.classes.graph.Graph object at 0x000001EB6D32E730>, <networkx.classes.graph.Graph object at 0x000001EB6D32E0D0>, <networkx.classes.graph.Graph object at 0x000001EB6D32E790>, <networkx.classes.graph.Graph object at 0x000001EB6D32E550>, <networkx.classes.graph.Graph object at 0x000001EB6D32E7F0>, <networkx.classes.graph.Graph object at 0x000001EB6D32E820>, <networkx.classes.graph.Graph object at 0x000001EB6D32E850>, <networkx.classes.graph

In [34]:
print(node_labels)

[1, 2, 4, 5, 8, 10, 16, 17, 32, 33, 34, 36, 39]


In [35]:
print(edge_labels)

[1, 2, 4, 8, 16, 32, 64, 128, 256, 384, 512, 1024, 1152, 1536, 1664, 2048, 2560]


In [36]:
##################### Clustering Analysis Start Here #############################
def genCountMatrix(graphs,node_labels,edge_labels,typeCode,matrix_type="full",method="simple",join_labels=True,filename="count_matrix.csv",path=""):
	
	node_labels = {k:v for v,k in enumerate(node_labels)}
	matrix_label_set = set()
	count_array = np.empty([len(graphs)],dtype=object)
	count_graph = 0

	if method == 'path':
		for g in graphs:
			shortPaths = [i for i in nx.all_pairs_shortest_path_length(g)]
			shortPaths = {i[0]:i[1] for i in shortPaths}

			temp = dict()
			for i in g.nodes:
				
				for j in g.nodes:
					if i >= j:
						continue
					
					labels = [g.nodes[i]["type"],g.nodes[j]["type"]]
					shortest_length = shortPaths[i][j]

					if join_labels:
						labels = [[l] for l in labels]
					else:
						labels = [mask.code(l) for l in labels]
					
					for l1 in labels[0]:
						for l2 in labels[1]:
							temp_labels = sorted(map(lambda x: node_labels[x],[l1,l2]))
							
							label = "%d-%d-%d"%(temp_labels[0],temp_labels[1],shortest_length)
							matrix_label_set.add(label)

							if matrix_type == "full":
								temp[label] = temp.get(label,0) + 1
							elif matrix_type == "bin":
								temp[label] = temp.get(label,1)

			count_array[count_graph] = temp
			count_graph += 1
	else:
		for g in graphs:
			temp = dict()
			for e in g.edges():
				labels = [g.nodes[e[0]]["type"],g.nodes[e[1]]["type"]]
				
				#### Added after join labels 
				if join_labels:
					labels = [[l] for l in labels]
				else:
					labels = [mask.code(l) for l in labels]
				
				for l1 in labels[0]:
					for l2 in labels[1]:
						temp_labels = sorted(map(lambda x: node_labels[x],[l1,l2]))
					
						label = "%d-%d"%(temp_labels[0],temp_labels[1])
						matrix_label_set.add(label)

						if matrix_type == "full":
							temp[label] = temp.get(label,0) + 1
						elif matrix_type == "bin":
							temp[label] = temp.get(label,1)

			count_array[count_graph] = temp
			count_graph += 1

	matrix_label_set = [i for i in matrix_label_set]
	matrix_label_set.sort()
	
	count_matrix = np.zeros([len(graphs),len(matrix_label_set)],dtype=int)

	for i in range(len(count_array)):
		for j in range(len(matrix_label_set)):			
			count_matrix[i][j] = count_array[i].get(matrix_label_set[j],0)
	
	ct_mtx_path = Path(path)/filename
	np.savetxt(ct_mtx_path,count_matrix,fmt='%d', delimiter=",")

	return count_matrix	




In [37]:
	count_matrix_filename = "count_matrix.csv"
	if not (Path(path)/count_matrix_filename).exists():
		logging.info("---Generate counting matrix---")

		count_matrix = genCountMatrix(
					graphs,node_labels,edge_labels,typeCode,
					filename=count_matrix_filename,path=path)

	else:
		logging.info("---Load counting matrix---")
		count_matrix = np.genfromtxt((Path(path)/count_matrix_filename), delimiter=',')

INFO:root:---Load counting matrix---


In [38]:
print(count_matrix)

[[0. 0. 0. ... 0. 1. 0.]
 [2. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [39]:
class SVD: 

	def __init__(self,count_matrix,scaler='std',with_std=False):
		self.scaler = scaler
		self.with_std = with_std
		self.runSVD(count_matrix)

	def runSVD(self,matrix):
		if self.scaler == "mabs":
			scaler_obj = MaxAbsScaler()
			X = scaler_obj.fit_transform(matrix)
		elif self.scaler == "std":
			scaler_obj = StandardScaler(with_std=self.with_std).fit(matrix)
			X = scaler_obj.fit_transform(matrix)

		self.U, self.s , self.v = np.linalg.svd(X,full_matrices=True)

	def getReduced(self,n_components=0):
		U = self.U
		s = self.s
		if n_components == 0:
			n_components = s.shape[0]
		matrix = -np.dot(U[:,:n_components],np.diag(s[:n_components]))

		return matrix

	def saveReduced(self,n_components=0,file='foo.csv'):
		np.savetxt(file, self.getReduced(n_components), fmt='%f',delimiter=",") 

	def getVarianceComposition(self,n=0):
		s = self.s
		var_comp = [0]
		for i in range(s.shape[0]):
			var_comp.append(var_comp[i]+s[i]*s[i])

		var_comp = [i for i in map(lambda x: x/var_comp[-1],var_comp)]

		if n == 0:
			return var_comp
		if 0 < n <= s.shape[0]:
			return var_comp[n]
		return 0

    
def find_n_clusters(count_matrix):
	n_counter = dict()
	max_gap_connected = dict()
	smallest_neighbors = count_matrix.shape[0]
	svd = SVD(count_matrix,scaler='std',with_std=False)
	var_comp = svd.getVarianceComposition()
	
	idx = 0
	while var_comp[idx] < 0.95:
		idx += 1

	cl_range = [i for i in range(idx,count_matrix.shape[1]+1)]

	for n_components in cl_range:				
		data_matrix = svd.getReduced(n_components)

		for factor in np.arange(0.01,0.91,0.01):
			n_neighbors = int(factor*data_matrix.shape[0])
			n_cluster, connected = eg.calculate_gap(data_matrix,
											n_neighbors=n_neighbors)
			if connected:
				max_gap_connected[n_components] = (n_cluster,n_neighbors)
				if n_neighbors < smallest_neighbors:
					smallest_neighbors = n_neighbors
					n_counter = dict()

				if n_neighbors == smallest_neighbors:
					n_counter[n_cluster] = n_counter.get(n_cluster,0) + 1

				break

	n_clusters = max(n_counter.items(),key= lambda x: x[1])[0]			
	n_cluster_candidates = list(filter(lambda x: x[1][1] == smallest_neighbors and x[1][0] == n_clusters,max_gap_connected.items()))
	i = int((len(n_cluster_candidates)-0.25)/2)
	params = n_cluster_candidates[i]

	#Returns n_components, n_clusters, k_neighbors
	return params[0],params[1][0],params[1][1], svd.getReduced(params[0])

In [40]:
def spectral(data_matrix,n_clusters,n_neighbors=10):


	X_r = data_matrix
	algorithm = 'spectral'

	spectral = cl.SpectralClustering(n_clusters=n_clusters,
		affinity='nearest_neighbors',n_neighbors=n_neighbors)
	spectral.fit(X_r)
	
	y_pred = spectral.labels_.astype(np.int)
	return y_pred

In [44]:
def read_clusters(clusters,graphs,path=""):
	if isinstance(clusters,str):
		try:
			file = (Path(path)/clusters).open()
			clusters = np.loadtxt(file,dtype=int,delimiter=",")
		except IOError as e:
			raise e
	#else:
	
	#clusters = []
	graphs_dict = dict()

	#Construct dictionary structure
	for key,graph in zip(clusters,graphs):
		graphs_dict[key] = graphs_dict.get(key,[]) + [graph]

	return graphs_dict



In [53]:
	from pathlib import Path 
	from sklearn.preprocessing import StandardScaler
	import eigen_gap as eg
	from sklearn import cluster as cl
##################### Clustering #############################
	if not (Path(path)/"clusters.csv").exists():
		
		### Run SVD
		logging.info("---Run SVD on matrix---")

		n_components, n_clusters, k_neighbors, data_matrix = find_n_clusters(count_matrix)
				 
		logging.info("---Run Clustering---")
		res_cluster = spectral(data_matrix,n_clusters,k_neighbors)
		
		clusters_file_name = "clusters.csv"
		
		with (Path(path)/clusters_file_name).open(mode="w") as clusters_file:
			np.savetxt(clusters_file,res_cluster,fmt='%i', delimiter=",")
		
		clusters = read_clusters(res_cluster,graphs)
	else:
		logging.info("---Load Clusters---")
		clusters_file_name = "clusters.csv"
		clusters = read_clusters(clusters_file_name,graphs,path=path)
        



INFO:root:---Run SVD on matrix---
INFO:root:---Run Clustering---
<ipython-input-40-7675c7661778>:11: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y_pred = spectral.labels_.astype(np.int)


In [54]:
print(n_components)

12


In [55]:
print(n_clusters)

10


In [56]:
print(k_neighbors)

35


In [57]:
print(data_matrix)

[[ 0.11603224  0.50536747  0.18625752 ... -0.06896146 -0.06094858
   0.01911088]
 [-0.98828756  0.24173169  0.22827253 ...  0.1273404  -0.31314772
   0.00462012]
 [ 0.25866866  1.22690559 -1.02251214 ...  0.01248427  0.01923235
  -0.00725281]
 ...
 [ 0.18666306  0.71571685 -0.55171593 ... -0.04028069 -0.03356156
   0.01155315]
 [ 0.39839629 -0.48840631  0.10755822 ... -0.02326913 -0.0222089
   0.0084622 ]
 [ 0.39839629 -0.48840631  0.10755822 ... -0.02326913 -0.0222089
   0.0084622 ]]


In [58]:
print(clusters)

{9: [<networkx.classes.graph.Graph object at 0x000001EB556574C0>, <networkx.classes.graph.Graph object at 0x000001EB6D32E5E0>, <networkx.classes.graph.Graph object at 0x000001EB6D32E730>, <networkx.classes.graph.Graph object at 0x000001EB6D32E580>, <networkx.classes.graph.Graph object at 0x000001EB6D32E760>, <networkx.classes.graph.Graph object at 0x000001EB6D32E610>, <networkx.classes.graph.Graph object at 0x000001EB6D32ED00>, <networkx.classes.graph.Graph object at 0x000001EB6D32ED30>, <networkx.classes.graph.Graph object at 0x000001EB6D32E6D0>, <networkx.classes.graph.Graph object at 0x000001EB6D3814C0>, <networkx.classes.graph.Graph object at 0x000001EB6D381250>, <networkx.classes.graph.Graph object at 0x000001EB6D381520>, <networkx.classes.graph.Graph object at 0x000001EB6D381130>, <networkx.classes.graph.Graph object at 0x000001EB6D381580>, <networkx.classes.graph.Graph object at 0x000001EB6D381610>, <networkx.classes.graph.Graph object at 0x000001EB6D381670>, <networkx.classes.g